.TH WXKB_SWITCH 1 "November 2024" "1.0.1" "User Commands"
.SH NAME
wxkb_switch - Utility for switching keyboard layouts under Wayland window system.
.SH SYNOPSIS
.B wxkb_switch
.RI [ options ]
.SH DESCRIPTION
The
.B wxkb_switch
utility allows users to switch between different keyboard layouts under Wayland window system.
.SH OPTIONS
.TP
.B -h, --help
Display this help message.
.TP
.B -n, --next
Set next xkb layout.
.TP
.B -p, --prev
Set previous xkb layout.
.TP
.B -l, --list
List available layouts.
.TP
.B -v, --version
Print program version.
.TP
.B -d, --debug
Enable debug mode.
.SH SEE ALSO
.BR wxkb_switch,
.BR actkbd,
.BR xkb-switch,
.BR openswitcher.
.SH AUTHOR
Written by [Frolov Ruslan Victorovich] email [gald.rus@yandex.ru].