.TH WXKB-SWITCH 1 "June 2026" "1.0.4" "User Commands"
.SH NAME
wxkb-switch - Utility for switching keyboard layouts under Wayland window system.
Works under X11 window system too.
.SH SYNOPSIS
.B wxkb-switch
.RI [ options ]
.SH DESCRIPTION
The
.B wxkb-switch
utility allows users to switch between different keyboard layouts under Wayland window system.
.SH OPTIONS
.TP
.B -h, --help
Display this help message.
.TP
.B -n, --next
Set next xkb layout.
.TP
.B -p, --prev
Set previous xkb layout.
.TP
.B -l, --list
List available layouts.
.TP
.B -v, --version
Print program version.
.TP
.B -d, --debug
Enable debug mode.
.TP
.B -g, --gnome
Force execution under GNOME.
.SH SEE ALSO
.BR wxkb-switch,
.BR actkbd,
.BR xkb-switch.
.SH AUTHOR
Written by [Frolov Ruslan Victorovich] email [gald.rus@yandex.ru].
